
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alexis
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        File n = new File("./pokemon-wallpaper-hd-9.jpg");
        Image img = Toolkit.getDefaultToolkit().createImage(n.getPath()).getScaledInstance(817, 444, 0);
        b_login.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_register = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfr_nombre = new javax.swing.JTextField();
        jsr_edad = new javax.swing.JSpinner();
        tfr_usuario = new javax.swing.JTextField();
        tfr_contraseña = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        back_register = new javax.swing.JLabel();
        jd_Interface = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        cb_pokedex = new javax.swing.JComboBox<>();
        pokemon_listado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lista_poke = new javax.swing.JLabel();
        back_transferir = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rd_hombre = new javax.swing.JRadioButton();
        rd_mujer = new javax.swing.JRadioButton();
        rd_Shyny = new javax.swing.JRadioButton();
        js_peso = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        tf_habilidad1 = new javax.swing.JTextField();
        tf_habilidad2 = new javax.swing.JTextField();
        tf_habilidad3 = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        tf_apodo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_descripcion = new javax.swing.JTextArea();
        js_altura = new javax.swing.JSpinner();
        tf_categoria = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cb_debilidades = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        js_hp = new javax.swing.JSpinner();
        js_ataque = new javax.swing.JSpinner();
        js_defensa = new javax.swing.JSpinner();
        js_ataqueEspecial = new javax.swing.JSpinner();
        js_defensaEspecial = new javax.swing.JSpinner();
        js_velocidad = new javax.swing.JSpinner();
        tf_evolucion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        imgPokemon = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        back_agregar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        rdm_Hombre = new javax.swing.JRadioButton();
        rdm_Mujer = new javax.swing.JRadioButton();
        rdm_Shyny = new javax.swing.JRadioButton();
        jsm_Peso = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        tfm_habilidad1 = new javax.swing.JTextField();
        tfm_habilidad2 = new javax.swing.JTextField();
        tfm_habilidad3 = new javax.swing.JTextField();
        tfm_Nombre = new javax.swing.JTextField();
        tfm_Apodo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tam_Descripcion = new javax.swing.JTextArea();
        jsm_Altura = new javax.swing.JSpinner();
        tfm_Categoria = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cbm_Tipo = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        cbm_Debilidades = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jsm_hp = new javax.swing.JSpinner();
        jsm_ataque = new javax.swing.JSpinner();
        jsm_defensa = new javax.swing.JSpinner();
        jsm_ataqueEspecial = new javax.swing.JSpinner();
        jsm_defensaEspecial = new javax.swing.JSpinner();
        jsm_velocidad = new javax.swing.JSpinner();
        tf_evoluciones = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jlm_img = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        back_modificar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jb_Eliminar = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        back_Eliminar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cb_mios = new javax.swing.JComboBox<>();
        cb_usuarios = new javax.swing.JComboBox<>();
        jButton13 = new javax.swing.JButton();
        back_listar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        bg_Genero = new javax.swing.ButtonGroup();
        bgm_Genero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        b_login = new javax.swing.JLabel();

        jd_register.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre");
        jd_register.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel4.setText("Edad");
        jd_register.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel5.setText("Usuario");
        jd_register.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel6.setText("Contraseña");
        jd_register.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, -1));
        jd_register.getContentPane().add(tfr_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        jsr_edad.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));
        jd_register.getContentPane().add(jsr_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));
        jd_register.getContentPane().add(tfr_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, -1));
        jd_register.getContentPane().add(tfr_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, -1));

        jButton3.setText("Registrar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jd_register.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel7.setText("Bienvenido al Sistema de Registro del Pueblo Palleta");
        jd_register.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));
        jd_register.getContentPane().add(back_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Seleccione al Pokemon");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        cb_pokedex.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_pokedexItemStateChanged(evt);
            }
        });
        cb_pokedex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_pokedexMouseClicked(evt);
            }
        });
        jPanel5.add(cb_pokedex, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 270, -1));

        pokemon_listado.setText("Seleccionar Pokemon");
        pokemon_listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pokemon_listadoMouseClicked(evt);
            }
        });
        jPanel5.add(pokemon_listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 160, 80));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 480, 380));
        jPanel5.add(lista_poke, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 350, 250));
        jPanel5.add(back_transferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 900, 460));

        jTabbedPane1.addTab("Pokedex", jPanel5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Nombre");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 49, -1, -1));

        jLabel9.setText("Apodo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 81, -1, -1));

        jLabel10.setText("Descripcion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, -1, -1));

        jLabel11.setText("Altura");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 209, -1, -1));

        jLabel12.setText("Categoria");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 247, -1, -1));

        jLabel13.setText("Peso");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 284, -1, -1));

        jLabel14.setText("Genero");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 310, -1, -1));

        jLabel15.setText("Habilidades");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 340, -1, -1));

        bg_Genero.add(rd_hombre);
        rd_hombre.setText("Hombre");
        jPanel1.add(rd_hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 306, -1, -1));

        bg_Genero.add(rd_mujer);
        rd_mujer.setText("Mujer");
        jPanel1.add(rd_mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 306, -1, -1));

        bg_Genero.add(rd_Shyny);
        rd_Shyny.setText("Shyny");
        jPanel1.add(rd_Shyny, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 306, -1, -1));

        js_peso.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 9999.0d, 0.1d));
        jPanel1.add(js_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 274, -1, -1));

        jLabel16.setText("Kg.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 284, -1, -1));
        jPanel1.add(tf_habilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 335, 90, -1));
        jPanel1.add(tf_habilidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 335, 90, -1));
        jPanel1.add(tf_habilidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 335, 90, -1));
        jPanel1.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 44, 200, -1));
        jPanel1.add(tf_apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 76, 200, -1));

        tf_descripcion.setColumns(20);
        tf_descripcion.setRows(5);
        jScrollPane1.setViewportView(tf_descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 114, -1, -1));

        js_altura.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 9999.0d, 0.1d));
        jPanel1.add(js_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 204, -1, -1));
        jPanel1.add(tf_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 242, 200, -1));

        jLabel17.setText("m.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 209, -1, -1));

        jLabel18.setText("Tipo");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 372, -1, -1));

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acero", "Agua", "Bicho", "Dragon", "Electrico", "Fantasma", "Fuego", "Hada", "Hielo", "Lucha", "Normal", "Planta", "Psiquico", "Tierra", "Roca", "Siniestro", "Veneno", "Volador", "???" }));
        jPanel1.add(cb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 368, -1, -1));

        jLabel19.setText("Debilidades");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 407, -1, -1));

        cb_debilidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acero", "Agua", "Bicho", "Dragon", "Electrico", "Fantasma", "Fuego", "Hada", "Hielo", "Lucha", "Normal", "Planta", "Psiquico", "Tierra", "Roca", "Siniestro", "Veneno", "Volador", "???" }));
        jPanel1.add(cb_debilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 403, -1, -1));

        jButton4.setText("Añadir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 367, -1, -1));

        jButton5.setText("Añadir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 402, -1, -1));

        jLabel20.setText("HP");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 44, -1, -1));

        jLabel21.setText("Ataque");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 76, -1, -1));

        jLabel22.setText("Defensa");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 108, -1, -1));

        jLabel23.setText("Ataque Especial");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 146, -1, -1));

        jLabel24.setText("Defensa Especial");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 178, -1, -1));

        jLabel25.setText("Velocidad");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 210, -1, -1));

        jLabel26.setText("Evoluciones");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 242, -1, -1));

        js_hp.setModel(new javax.swing.SpinnerNumberModel(1, 0, 9999, 1));
        jPanel1.add(js_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 44, -1, -1));

        js_ataque.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel1.add(js_ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 76, -1, -1));

        js_defensa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel1.add(js_defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 108, -1, -1));

        js_ataqueEspecial.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel1.add(js_ataqueEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 146, -1, -1));

        js_defensaEspecial.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel1.add(js_defensaEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 178, -1, -1));

        js_velocidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel1.add(js_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 210, -1, -1));
        jPanel1.add(tf_evolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 242, 85, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 0, -1, 458));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 44, -1, 236));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 44, -1, 236));
        jPanel1.add(imgPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 44, 187, 178));

        jButton6.setText("Cargar Imagen");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 240, -1, -1));

        jButton12.setText("Guardar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 298, -1, -1));
        jPanel1.add(back_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Nombre");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 49, -1, -1));

        jLabel29.setText("Apodo");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 81, -1, -1));

        jLabel30.setText("Descripcion");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, -1, -1));

        jLabel31.setText("Altura");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 211, -1, -1));

        jLabel32.setText("Categoria");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 249, -1, -1));

        jLabel33.setText("Peso");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 286, -1, -1));

        jLabel34.setText("Genero");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 312, -1, -1));

        jLabel35.setText("Habilidades");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, -1, -1));

        bgm_Genero.add(rdm_Hombre);
        rdm_Hombre.setText("Hombre");
        jPanel2.add(rdm_Hombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 308, -1, -1));

        bgm_Genero.add(rdm_Mujer);
        rdm_Mujer.setText("Mujer");
        jPanel2.add(rdm_Mujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 308, -1, -1));

        bgm_Genero.add(rdm_Shyny);
        rdm_Shyny.setText("Shyny");
        jPanel2.add(rdm_Shyny, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 308, -1, -1));

        jsm_Peso.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 9999.0d, 0.1d));
        jPanel2.add(jsm_Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 276, -1, -1));

        jLabel36.setText("Kg.");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 286, -1, -1));
        jPanel2.add(tfm_habilidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 337, 90, -1));
        jPanel2.add(tfm_habilidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 337, 90, -1));
        jPanel2.add(tfm_habilidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 337, 90, -1));
        jPanel2.add(tfm_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 44, 200, -1));
        jPanel2.add(tfm_Apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 76, 200, -1));

        tam_Descripcion.setColumns(20);
        tam_Descripcion.setRows(5);
        jScrollPane2.setViewportView(tam_Descripcion);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 116, -1, -1));

        jsm_Altura.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 9999.0d, 0.1d));
        jPanel2.add(jsm_Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 206, -1, -1));
        jPanel2.add(tfm_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 244, 200, -1));

        jLabel37.setText("m.");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 211, -1, -1));

        jLabel38.setText("Tipo");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 374, -1, -1));

        cbm_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acero", "Agua", "Bicho", "Dragon", "Electrico", "Fantasma", "Fuego", "Hada", "Hielo", "Lucha", "Normal", "Planta", "Psiquico", "Tierra", "Roca", "Siniestro", "Veneno", "Volador", "???" }));
        jPanel2.add(cbm_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 370, -1, -1));

        jLabel39.setText("Debilidades");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 409, -1, -1));

        cbm_Debilidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acero", "Agua", "Bicho", "Dragon", "Electrico", "Fantasma", "Fuego", "Hada", "Hielo", "Lucha", "Normal", "Planta", "Psiquico", "Tierra", "Roca", "Siniestro", "Veneno", "Volador", "???" }));
        jPanel2.add(cbm_Debilidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 405, -1, -1));

        jButton7.setText("Añadir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 369, -1, -1));

        jButton8.setText("Añadir");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 404, -1, -1));

        jLabel40.setText("HP");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 44, -1, -1));

        jLabel41.setText("Ataque");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 76, -1, -1));

        jLabel42.setText("Defensa");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 108, -1, -1));

        jLabel43.setText("Ataque Especial");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 146, -1, -1));

        jLabel44.setText("Defensa Especial");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 178, -1, -1));

        jLabel45.setText("Velocidad");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 210, -1, -1));

        jLabel46.setText("Evoluciones");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 242, -1, -1));

        jsm_hp.setModel(new javax.swing.SpinnerNumberModel(1, 0, 9999, 1));
        jPanel2.add(jsm_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 44, -1, -1));

        jsm_ataque.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel2.add(jsm_ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 76, -1, -1));

        jsm_defensa.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel2.add(jsm_defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 108, -1, -1));

        jsm_ataqueEspecial.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel2.add(jsm_ataqueEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 146, -1, -1));

        jsm_defensaEspecial.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel2.add(jsm_defensaEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 178, -1, -1));

        jsm_velocidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9999, 1));
        jPanel2.add(jsm_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 210, -1, -1));
        jPanel2.add(tf_evoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 242, 85, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 0, -1, 460));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 44, -1, 236));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 44, -1, 236));
        jPanel2.add(jlm_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 44, 253, 178));

        jButton9.setText("Cargar Imagen");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 240, -1, -1));

        jButton11.setText("Guardar cambios");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, -1));
        jPanel2.add(back_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        jTabbedPane1.addTab("Modificar", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarMouseClicked(evt);
            }
        });
        jPanel3.add(jb_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 210, -1));

        jButton10.setText("Eliminar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Seleccione el pokemon a Eliminar");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, -1));
        jPanel3.add(back_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        jTabbedPane1.addTab("Eliminar", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_mios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_miosMouseClicked(evt);
            }
        });
        jPanel4.add(cb_mios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 220, -1));

        cb_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_usuariosMouseClicked(evt);
            }
        });
        jPanel4.add(cb_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 60, 250, -1));

        jButton13.setText("jButton13");
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));
        jPanel4.add(back_listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        jTabbedPane1.addTab("Transferir", jPanel4);

        jMenu1.setText("File");

        jMenuItem1.setText("Cerrar Sesion");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jd_Interface.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_InterfaceLayout = new javax.swing.GroupLayout(jd_Interface.getContentPane());
        jd_Interface.getContentPane().setLayout(jd_InterfaceLayout);
        jd_InterfaceLayout.setHorizontalGroup(
            jd_InterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jd_InterfaceLayout.setVerticalGroup(
            jd_InterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InterfaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));
        getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 143, 250, -1));
        getContentPane().add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 187, 250, -1));

        jButton1.setText("Registrarse");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 120, -1));

        jButton2.setText("Iniciar Sesion");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 120, -1));
        getContentPane().add(b_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 817, 444));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        File n = new File("./613933.jpg");
        Image img = Toolkit.getDefaultToolkit().createImage(n.getPath()).getScaledInstance(490, 360, 0);
        back_register.setIcon(new ImageIcon(img));
        this.jd_register.pack();
        this.jd_register.setModal(true);
        this.setLocationRelativeTo(this);
        this.jd_register.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        File file = new File("./" + tf_user.getText() + "/" + tf_user.getText() + ".txt");

        if (file.exists()) {
            try {
                Scanner contenido = new Scanner(file);
                contenido.useDelimiter("•");
                String user = contenido.next();
                String password = contenido.next();
                int age = Integer.parseInt(contenido.next());
                String nombre = contenido.next();
                User entrada = new User(age, nombre, user, password);
                if (user.equals(tf_user.getText()) && password.equals(pf_password.getText())) {
                    usuario = entrada;

                    File n = new File("./pokemon-wallpaper-hd-13.jpg");
                    Image img = Toolkit.getDefaultToolkit().createImage(n.getPath()).getScaledInstance(900, 460, 0);
                    back_agregar.setIcon(new ImageIcon(img));

                    File a = new File("./Pikachu-Wallpaper-HD-1024x576.png");
                    Image imga = Toolkit.getDefaultToolkit().createImage(a.getPath()).getScaledInstance(900, 460, 0);
                    back_Eliminar.setIcon(new ImageIcon(imga));

                    File a1 = new File("./pokemon_136497.jpg");
                    Image imga1 = Toolkit.getDefaultToolkit().createImage(a1.getPath()).getScaledInstance(900, 460, 0);
                    back_listar.setIcon(new ImageIcon(imga1));

                    File a2 = new File("./cc6d9fffa96d27971b10878869f550e9.jpg");
                    Image imga2 = Toolkit.getDefaultToolkit().createImage(a2.getPath()).getScaledInstance(900, 460, 0);
                    back_modificar.setIcon(new ImageIcon(imga2));

                    File a3 = new File("./Pokemon-Go-Pikachu-in-Pokeballs-HD-Wallpaper.jpg");
                    Image imga3 = Toolkit.getDefaultToolkit().createImage(a3.getPath()).getScaledInstance(900, 460, 0);
                    back_transferir.setIcon(new ImageIcon(imga3));

                    this.jd_Interface.pack();
                    this.jd_Interface.setModal(true);
                    this.setLocationRelativeTo(this);
                    this.jd_Interface.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al ingresar el usuario o password");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

        }


    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        File file = new File("./" + tfr_usuario.getText());
        file.mkdir();

        FileWriter flwriter = null;
        BufferedWriter bfwriter = null;
        try {
            //if (file.exists()) {
            //JOptionPane.showMessageDialog(null, "El usuario Ya existe!");
            //} else {
            flwriter = new FileWriter("./" + tfr_usuario.getText() + "/" + tfr_usuario.getText() + ".txt");

            bfwriter = new BufferedWriter(flwriter);
            String temporal = tfr_usuario.getText() + "•" + tfr_contraseña.getText() + "•" + jsr_edad.getValue() + "•" + tfr_nombre.getText();
            //bfwriter.append(tfr_usuario.getText());
            bfwriter.write(temporal);

            bfwriter.close();
            tfr_nombre.setText("");
            tfr_usuario.setText("");
            tfr_contraseña.setText("");
            jsr_edad.setValue(10);
            JOptionPane.showMessageDialog(null, "Se ha registrado exitosamente");
            //}
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo exploto al crear el archivo");
        } finally {
            if (flwriter != null) {
                try {
                    bfwriter.close();
                    flwriter.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

        //File archivo = new File("./"+tfr_usuario.getText()+"/"+tfr_usuario.getText()+".txt");

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        String nombre = tf_nombre.getText();
        String apodo = tf_apodo.getText();
        String descripcion = tf_descripcion.getText();
        double altura = (double) js_altura.getValue();
        //String alt = (String) js_altura.getValue();
        String categoria = tf_categoria.getText();
        double peso = (double) js_peso.getValue();
        String genero;
        if (rd_hombre.isSelected()) {
            genero = rd_hombre.getText();
        } else if (rd_mujer.isSelected()) {
            genero = rd_mujer.getText();
        } else {
            genero = rd_Shyny.getText();
        }
        ArrayList<String> hab = new ArrayList();
        hab.add(tf_habilidad1.getText());
        hab.add(tf_habilidad2.getText());
        hab.add(tf_habilidad3.getText());

        int vida = (int) js_hp.getValue();
        int ataque = (int) js_ataque.getValue();
        int defensa = (int) js_defensa.getValue();
        int ataqueEspecial = (int) js_ataqueEspecial.getValue();
        int defensaEspecial = (int) js_defensaEspecial.getValue();
        int velocidad = (int) js_velocidad.getValue();
        String evolucion = tf_evolucion.getText();

        if (tipo[1].equals("")) {
            tipo[1] = " ";
        }
        String[] tempo_tipo = new String[2];
        ArrayList<String> tempo_debil = debilidades;
        tempo_tipo = tipo;

        pokemon = new Pokemon(0, nombre, apodo, descripcion, (double) js_altura.getValue(), categoria, (double) js_peso.getValue(), genero, (int) js_hp.getValue(), (int) js_ataque.getValue(), (int) js_defensa.getValue(), (int) js_ataqueEspecial.getValue(), (int) js_defensaEspecial.getValue(), (int) js_velocidad.getValue(), evolucion, direccion);
        pokemon.setHabilidades(hab);
        pokemon.setTipo(tempo_tipo);
        pokemon.setDebilidades(tempo_debil);

        total = nombre + tf_apodo.getText() + apodo + descripcion + altura + categoria + peso + genero + tf_habilidad1.getText() + tf_habilidad2.getText() + tf_habilidad3.getText() + vida + ataque + defensa + ataqueEspecial + defensaEspecial + velocidad + evolucion + tipo[0] + tipo[1] + debilidades;

        String us = usuario.getUser();

        JOptionPane.showMessageDialog(null, "Usuario conectado: " + us);

        try {
            usuario.getPokedex().Agregar(pokemon, total.length());
            //usuario.getPokedex().Agregar(pokemon, total.length());
            JOptionPane.showMessageDialog(null, "Se guardo exitosamente el puchamon");

            tf_nombre.setText("");
            tf_apodo.setText("");
            tf_descripcion.setText("");
            js_altura.setValue(1);
            tf_categoria.setText("");
            js_peso.setValue(1);
            rd_hombre.setSelected(true);
            tf_habilidad1.setText("");
            tf_habilidad2.setText("");
            tf_habilidad3.setText("");
            hab = new ArrayList();
            tempo_debil = debilidades = new ArrayList();
            tempo_tipo = new String[2];
            cont = 0;

            js_hp.setValue(1);
            js_ataque.setValue(1);
            js_defensa.setValue(1);
            js_ataqueEspecial.setValue(1);
            js_defensaEspecial.setValue(1);
            js_velocidad.setValue(1);
            tf_evolucion.setText("");
            imgPokemon.setIcon(null);
            
            

        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(filtro);

        int regresaValor = fileChooser.showOpenDialog(null);
        if (regresaValor == JFileChooser.APPROVE_OPTION) {
            File archivoElegido = fileChooser.getSelectedFile();
            direccion = archivoElegido.getPath();
            try {
                ImageIcon icon = new ImageIcon(direccion);
                imgPokemon.setIcon(icon);
            } catch (Exception es) {
                JOptionPane.showMessageDialog(null, "Exploto algo al cargar la imagen" + es);
            }
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        debilidades.add(cb_debilidades.getSelectedItem().toString());
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (cont == 2) {
            JOptionPane.showMessageDialog(null, "Ha alcanzado el limite de habilidades");
        } else if (cont == 0) {
            String tipos = cb_tipo.getSelectedItem().toString();
            tipo[0] = tipos;
            cont++;
        } else if (cont == 1) {
            String tipos = cb_tipo.getSelectedItem().toString();
            tipo[1] = tipos;
            cont++;
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void pokemon_listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pokemon_listadoMouseClicked
        jTextArea1.setText(((Pokemon) cb_pokedex.getSelectedItem()).toString());
        File as = new File(((Pokemon) cb_pokedex.getSelectedItem()).getImagen());
        Image img = Toolkit.getDefaultToolkit().createImage(as.getPath()).getScaledInstance(240, 190, 0);
        lista_poke.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_pokemon_listadoMouseClicked

    private void cb_pokedexItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_pokedexItemStateChanged
        cb_pokedex.getSelectedItem();
    }//GEN-LAST:event_cb_pokedexItemStateChanged

    private void jb_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarMouseClicked
        try {
            ArrayList<Pokemon> poke = usuario.getPokedex().Listar();

            DefaultComboBoxModel x = new DefaultComboBoxModel();
            for (int i = 0; i < poke.size(); i++) {
                x.addElement(poke.get(i));
            }
            jb_Eliminar.setModel(x);

        } catch (FileNotFoundException ex) {

        }

    }//GEN-LAST:event_jb_EliminarMouseClicked

    private void cb_pokedexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_pokedexMouseClicked
        try {
            ArrayList<Pokemon> poke = usuario.getPokedex().Listar();

            DefaultComboBoxModel x = new DefaultComboBoxModel();
            for (int i = 0; i < poke.size(); i++) {
                x.addElement(poke.get(i));
            }
            cb_pokedex.setModel(x);

        } catch (FileNotFoundException ex) {

        }
    }//GEN-LAST:event_cb_pokedexMouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        try {
            usuario.getPokedex().Borrar((Pokemon) jb_Eliminar.getSelectedItem());
            if (!prior.ColaVacia()) {
                File brr = new File("./"+usuario.getUser()+"/"+usuario.getUser()+"_pokeb.txt");
                ArrayList<String> nodos = new ArrayList();
                
                Scanner sc = new Scanner(brr);
                sc.useDelimiter("☼");
                while(sc.hasNext()){
                    nodos.add(sc.next());
                }
                Pokemon x=((Pokemon) jb_Eliminar.getSelectedItem());
                int posicion=usuario.getPokedex().Buscar(x);
                String y="";
                String altura=""+x.getAltura();
                String peso=""+x.getPeso();
                String vida=""+x.getHp();
                String ataque=""+x.getAtaque();
                String Defensa=""+x.getDefensa();
                String A_esp=""+x.getAtaque_Especial();
                String d_esp=""+x.getDefensa_Especial();
                String vel=""+x.getVelocidad();
                y=y+x.getNombre().length()+x.getApodo()+x.getDescripcion()+altura+x.getCategoria()+peso+x.getGenero()+vida+ataque+Defensa+A_esp+d_esp+vel+x.getEvolucion()+x.getImagen()+x.getTipo()[0]+x.getTipo()[1];
                for (int i = 0; i < x.getDebilidades().size(); i++) {
                    y=y+x.getDebilidades().get(i);
                }
                for (int i = 0; i < x.getHabilidades().size(); i++) {
                    y=y+x.getHabilidades().get(i);
                }
                FileWriter filewriter = null;
                BufferedWriter bufferedwriter = null;
                String res=""+posicion+","+y.length();
                nodos.add(res);
                String fin="";
                for (int i = 0; i < nodos.size(); i++) {
                    fin=fin+"☼"+nodos.get(i);
                }
        try {
            filewriter = new FileWriter(brr, false);
            bufferedwriter = new BufferedWriter(filewriter);
            bufferedwriter.write(fin);
            bufferedwriter.flush();
        } catch (Exception e) {

        }
            }else{
                
            }
            JOptionPane.showMessageDialog(null, "Se ha liberado a su pokemon :(");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Algo paso al Eliminar pokemon");
        }


    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        String nombre = tfm_Nombre.getText();
        String apodo = tfm_Apodo.getText();
        String descripcion = tam_Descripcion.getText();
        double altura = (double) jsm_Altura.getValue();
        //String alt = (String) js_altura.getValue();
        String categoria = tfm_Categoria.getText();
        double peso = (double) jsm_Peso.getValue();
        String genero;
        if (rd_hombre.isSelected()) {
            genero = rdm_Hombre.getText();
        } else if (rd_mujer.isSelected()) {
            genero = rdm_Mujer.getText();
        } else {
            genero = rdm_Shyny.getText();
        }
        ArrayList<String> hab = new ArrayList();
        hab.add(tfm_habilidad1.getText());
        hab.add(tfm_habilidad2.getText());
        hab.add(tfm_habilidad3.getText());

        int vida = (int) jsm_hp.getValue();
        int ataque = (int) jsm_ataque.getValue();
        int defensa = (int) jsm_defensa.getValue();
        int ataqueEspecial = (int) jsm_ataqueEspecial.getValue();
        int defensaEspecial = (int) jsm_defensaEspecial.getValue();
        int velocidad = (int) jsm_velocidad.getValue();
        String evolucion = tf_evoluciones.getText();

        if (tipo[1].equals("")) {
            tipo[1] = " ";
        }
        String[] tempo_tipo = new String[2];
        ArrayList<String> tempo_debil = debilidades;
        tempo_tipo = tipo;

        pokemon = new Pokemon(0, nombre, apodo, descripcion, (double) jsm_Altura.getValue(), categoria, (double) jsm_Peso.getValue(), genero, (int) jsm_hp.getValue(), (int) jsm_ataque.getValue(), (int) jsm_defensa.getValue(), (int) jsm_ataqueEspecial.getValue(), (int) jsm_defensaEspecial.getValue(), (int) jsm_velocidad.getValue(), evolucion, direccionm);
        pokemon.setHabilidades(hab);
        pokemon.setTipo(tempo_tipo);
        pokemon.setDebilidades(tempo_debil);

        total = nombre + tf_apodo.getText() + apodo + descripcion + altura + categoria + peso + genero + tfm_habilidad1.getText() + tfm_habilidad2.getText() + tfm_habilidad3.getText() + vida + ataque + defensa + ataqueEspecial + defensaEspecial + velocidad + evolucion + tipo[0] + tipo[1] + debilidades;

        String us = usuario.getUser();

        JOptionPane.showMessageDialog(null, "Usuario conectado: " + us);
        
        
        try {
            usuario.getPokedex().Modificar((Pokemon)jComboBox1.getSelectedItem(), pokemon);
            //usuario.getPokedex().Agregar(pokemon, total.length());
            JOptionPane.showMessageDialog(null, "Se guardo exitosamente el puchamon");

            tfm_Nombre.setText("");
            tfm_Apodo.setText("");
            tf_descripcion.setText("");
            jsm_Altura.setValue(1);
            tfm_Categoria.setText("");
            jsm_Peso.setValue(1);
            rdm_Hombre.setSelected(true);
            tfm_habilidad1.setText("");
            tfm_habilidad2.setText("");
            tfm_habilidad3.setText("");
            hab = new ArrayList();
            tempo_debil = debilidades = new ArrayList();
            tempo_tipo = new String[2];
            cont = 0;

            jsm_hp.setValue(1);
            jsm_ataque.setValue(1);
            jsm_defensa.setValue(1);
            jsm_ataqueEspecial.setValue(1);
            jsm_defensaEspecial.setValue(1);
            jsm_velocidad.setValue(1);
            tf_evoluciones.setText("");
            imgPokemon.setIcon(null);
            
            

        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        try {
            ArrayList<Pokemon> poke1 = usuario.getPokedex().Listar();

            DefaultComboBoxModel x = new DefaultComboBoxModel();
            for (int i = 0; i < poke1.size(); i++) {
                x.addElement(poke1.get(i));
            }
            jComboBox1.setModel(x);

        } catch (FileNotFoundException ex) {

        }
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if (cont == 2) {
            JOptionPane.showMessageDialog(null, "Ha alcanzado el limite de habilidades");
        } else if (cont == 0) {
            String tipos = cb_tipo.getSelectedItem().toString();
            tipo[0] = tipos;
            cont++;
        } else if (cont == 1) {
            String tipos = cb_tipo.getSelectedItem().toString();
            tipo[1] = tipos;
            cont++;
        }    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        debilidades.add(cb_debilidades.getSelectedItem().toString());
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
    JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(filtro);

        int regresaValor = fileChooser.showOpenDialog(null);
        if (regresaValor == JFileChooser.APPROVE_OPTION) {
            File archivoElegido = fileChooser.getSelectedFile();
            direccionm = archivoElegido.getPath();
            try {
                ImageIcon icon = new ImageIcon(direccionm);
                jlm_img.setIcon(icon);
            } catch (Exception es) {
                JOptionPane.showMessageDialog(null, "Exploto algo al cargar la imagen" + es);
            }
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void cb_miosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_miosMouseClicked
        try {
            ArrayList<Pokemon> poke = usuario.getPokedex().Listar();

            DefaultComboBoxModel x = new DefaultComboBoxModel();
            for (int i = 0; i < poke.size(); i++) {
                x.addElement(poke.get(i));
            }
            cb_mios.setModel(x);

        } catch (FileNotFoundException ex) {

        }
    }//GEN-LAST:event_cb_miosMouseClicked

    private void cb_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_usuariosMouseClicked
    try {
            ArrayList<Pokemon> poke = usuario.getPokedex().Listar();

            DefaultComboBoxModel x = new DefaultComboBoxModel();
            for (int i = 0; i < poke.size(); i++) {
                x.addElement(poke.get(i));
            }
            cb_mios.setModel(x);

        } catch (FileNotFoundException ex) {

        }
    }//GEN-LAST:event_cb_usuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_login;
    private javax.swing.JLabel back_Eliminar;
    private javax.swing.JLabel back_agregar;
    private javax.swing.JLabel back_listar;
    private javax.swing.JLabel back_modificar;
    private javax.swing.JLabel back_register;
    private javax.swing.JLabel back_transferir;
    private javax.swing.ButtonGroup bg_Genero;
    private javax.swing.ButtonGroup bgm_Genero;
    private javax.swing.JComboBox<String> cb_debilidades;
    private javax.swing.JComboBox<String> cb_mios;
    private javax.swing.JComboBox<String> cb_pokedex;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_usuarios;
    private javax.swing.JComboBox<String> cbm_Debilidades;
    private javax.swing.JComboBox<String> cbm_Tipo;
    private javax.swing.JLabel imgPokemon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jb_Eliminar;
    private javax.swing.JDialog jd_Interface;
    private javax.swing.JDialog jd_register;
    private javax.swing.JLabel jlm_img;
    private javax.swing.JSpinner js_altura;
    private javax.swing.JSpinner js_ataque;
    private javax.swing.JSpinner js_ataqueEspecial;
    private javax.swing.JSpinner js_defensa;
    private javax.swing.JSpinner js_defensaEspecial;
    private javax.swing.JSpinner js_hp;
    private javax.swing.JSpinner js_peso;
    private javax.swing.JSpinner js_velocidad;
    private javax.swing.JSpinner jsm_Altura;
    private javax.swing.JSpinner jsm_Peso;
    private javax.swing.JSpinner jsm_ataque;
    private javax.swing.JSpinner jsm_ataqueEspecial;
    private javax.swing.JSpinner jsm_defensa;
    private javax.swing.JSpinner jsm_defensaEspecial;
    private javax.swing.JSpinner jsm_hp;
    private javax.swing.JSpinner jsm_velocidad;
    private javax.swing.JSpinner jsr_edad;
    private javax.swing.JLabel lista_poke;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JButton pokemon_listado;
    private javax.swing.JRadioButton rd_Shyny;
    private javax.swing.JRadioButton rd_hombre;
    private javax.swing.JRadioButton rd_mujer;
    private javax.swing.JRadioButton rdm_Hombre;
    private javax.swing.JRadioButton rdm_Mujer;
    private javax.swing.JRadioButton rdm_Shyny;
    private javax.swing.JTextArea tam_Descripcion;
    private javax.swing.JTextField tf_apodo;
    private javax.swing.JTextField tf_categoria;
    private javax.swing.JTextArea tf_descripcion;
    private javax.swing.JTextField tf_evolucion;
    private javax.swing.JTextField tf_evoluciones;
    private javax.swing.JTextField tf_habilidad1;
    private javax.swing.JTextField tf_habilidad2;
    private javax.swing.JTextField tf_habilidad3;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tfm_Apodo;
    private javax.swing.JTextField tfm_Categoria;
    private javax.swing.JTextField tfm_Nombre;
    private javax.swing.JTextField tfm_habilidad1;
    private javax.swing.JTextField tfm_habilidad2;
    private javax.swing.JTextField tfm_habilidad3;
    private javax.swing.JTextField tfr_contraseña;
    private javax.swing.JTextField tfr_nombre;
    private javax.swing.JTextField tfr_usuario;
    // End of variables declaration//GEN-END:variables

    TDA_Archivo archivo = new TDA_Archivo();
    Pokemon pokemon;
    String[] tipo = new String[2];
    ArrayList<String> debilidades = new ArrayList();
    int cont = 0;
    String direccion;
    String direccionm;
    String total;
    User usuario;

    private Writer FileWriter(File flwriter) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    Priority prior;
    
}
